<?php

namespace AppBundle\Repository;

/**
 * SlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMaxSuiteNumber($subThematic)
    {
        $query = $this->createQueryBuilder('s');
        $query->select('MAX(s.suiteNumber) AS max_suite_number');
        $query->andWhere('s.thematic = :subThematic');
        $query->setParameter('subThematic', $subThematic);

        return $query->getQuery()->getSingleScalarResult();
    }
}
