<?php

namespace AppBundle\Repository;

/**
 * StatisticalUserThematicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticalUserThematicRepository extends \Doctrine\ORM\EntityRepository
{
}
