<?php

namespace AppBundle\Repository;

/**
 * StatsSubThematicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsSubThematicRepository extends \Doctrine\ORM\EntityRepository
{
}
