<?php

namespace AppBundle\Repository;

/**
 * StatisticalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticalRepository extends \Doctrine\ORM\EntityRepository
{
}
