<?php

namespace AppBundle\Repository;

/**
 * StatsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsUserRepository extends \Doctrine\ORM\EntityRepository
{
}
