<?php

namespace AppBundle\Repository;

/**
 * StatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
