<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ThematicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThematicRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByPage($page, $params = array())
    {
        $qb = $this->createQueryBuilder('t');

        foreach ($params as $key => $param) {
            $qb->andWhere('t.' . $key . ' = :' . $key)->setParameter($key, $param);
        }

        $qb->andWhere('t.parentThematic IS NULL');
        $qb->orderBy("t.suiteNumber", 'ASC');
        $qb->setFirstResult(($page - 1) * 20)->setMaxResults(20);

        return new Paginator($qb, true);
    }

    public function getMaxSuiteNumber($offer = null, $parentThematic = null)
    {
        $query = $this->createQueryBuilder('t');
        $query->select('MAX(t.suiteNumber) AS max_suite_number');

        if ($offer) {
            $query->andWhere('t.offer = :offer');
            $query->setParameter('offer', $offer);
        } else {
            $query->andWhere('t.offer IS NULL');
        }

        if ($parentThematic) {
            $query->andWhere('t.parentThematic = :parentThematic');
            $query->setParameter('parentThematic', $parentThematic);
        } else {
            $query->andWhere('t.parentThematic IS NULL');
        }

        return $query->getQuery()->getSingleScalarResult();
    }
}
