<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getClientsByPage($page, $params = array())
    {
        $qb = $this->createQueryBuilder('u')
            ->andWhere("u.username NOT LIKE 'admin'")
            ->orderBy('u.createdAt', 'DESC');

        foreach ($params as $key => $param) {
            $qb->andWhere('u.' . $key . ' = :' . $key)->setParameter($key, $param);
        }

        $qb->setFirstResult(($page - 1) * 20)->setMaxResults(20);

        return new Paginator($qb, true);
    }
}
