liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/uploads
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        big:
            filters:
                resize: { size: [1000, 800] }
        medium:
            filters:
                resize: { size: [800, 600] }
        small:
            filters:
                resize: { size: [220, 110] }
        thematic:
            filters:
                resize: { size: [475, 300] }
        sub_thematic:
            filters:
                resize: { size: [250, 158] }
        slide:
            filters:
                resize: { size: [1000, 566] }
        thumbnail:
            filters:
                thumbnail: { size: [500, 280], mode: inset }
        logo:
            filters:
                relative_resize:
                    heighten: 40
