#FosUserBundle routes
admin_login:
    path:  /saSecureAlliance/login
    defaults: { _controller: FOSUserBundle:Security:login }

admin_check:
    path:  /saSecureAlliance/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

admin_logout:
    path:  /saSecureAlliance/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#LiipImagine routes
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#Froala routes
kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor

#Custom routes
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /



